server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8888/eureka

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: article-reply
          uri: lb://INNERJOINUS-ARTICLEREPLY
          predicates:
            - Path=/article-reply/**
          filters:
            - RewritePath=/article-reply/(?<segment>.*), /$\{segment}

        - id: studygroup-member
          uri: lb://INNERJOINUS-STUDYGROUP-MEMBER
          predicates:
            - Path=/studygroup-member/**
          filters:
            - RewritePath=/studygroup-member/(?<segment>.*), /$\{segment}

        - id: user
          uri: lb://INNERJOINUS-USER
          predicates:
            - Path=/user/**
            - Method=GET
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user
          uri: lb://INNERJOINUS-USER
          predicates:
            - Path=/user/create
            - Method=POST
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

        - id: user
          uri: lb://INNERJOINUS-USER
          predicates:
            - Path=/user/login
          filters:
            - RewritePath=/user/(?<segment>.*), /$\{segment}

#        - id: user
#          uri: lb://INNERJOINUS-USER
#          predicates:
#            - Path=/user/**
#          filters:
#            - RewritePath=/user/(?<segment>.*), /$\{segment}

token:
  secret: l1Z5I9WufSD5qM0UTHXDJa1kaGxBlyhKMbx+ONkqzeRTlKdF8Bq37mA3Z8nhjRlwVUrL/u3bdkFeamIrUoWvVw==